//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int Id { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Valor { get; set; }
        public Nullable<int> Atencion { get; set; }
    
        public virtual Atencion Atencion1 { get; set; }
    }
}
