//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mascota()
        {
            this.Atencion = new HashSet<Atencion>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> Categoria { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<byte> Sexo { get; set; }
        public Nullable<byte> Esterilazado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atencion> Atencion { get; set; }
        public virtual Categoria Categoria1 { get; set; }
        public virtual Cliente Cliente1 { get; set; }
    }
}
